# -*- coding: utf-8 -*-
"""practice

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jkWVZdUTtZpGyEEV2ho4vFTYOhIVKWr1

random passward generator
"""

import random
import string

length= int(input("How long you want the passward to be?: "))
uppercase = input("Do you want uppercase in your passward? (Yes/No): ").strip().lower()
lowercase = input("Do you want lowercase in your passward? (Yes/No): ").strip().lower()
numbers = input("Do you want numbers in your passward? (Yes/No): ").strip().lower()
symbols = input("Do you want symbols in your passward? (Yes/No): ").strip().lower()

while True:
    if length <5:
      print("Too short length. Appropriate length is between 5 to 20")
      length= int(input("How long you want the passward to be?: "))
    elif length > 20:
      print("Too long length. Appropriate length is between 5 to 20")
      length= int(input("How long you want the passward to be?: "))
    else:
      print("Got it!!")
      break

lower= string.ascii_lowercase
upper= string.ascii_uppercase if uppercase == "yes" else ""
number= string.digits if numbers == "yes" else ""
symbol= string.punctuation if symbols == "yes" else ""

final_passward= lower+upper+number+symbol

required_character=[]
if uppercase == "yes":
  required_character.append(random.choice(upper))
if numbers == "yes":
  required_character.append(random.choice(number))
if symbols == "yes":
  required_character.append(random.choice(symbol))

remaining_length= length- len(required_character)
passward= required_character

for _ in range (remaining_length):
  character= random.choice (final_passward)
  passward.append(character)
random.shuffle (passward)
str_passward= "".join(passward)
print(f"Your passward is: {str_passward}")